config/routes.rb
Chessonrails::Application.routes.draw do

  devise_for :users
  root 'games#index'

  resources :games, :only => [:show, :new, :create, :update]

  resources :pieces, :only => [:update] do
    member do
     get 'select'
     get 'move'
     get 'switch'
    end
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :player_white, :class_name => 'User'
  belongs_to :player_black, :class_name => 'User'

  has_many :pieces

  validates :player_white_id, :numericality => {only_integer: true}
  validates :player_black_id, :numericality => {only_integer: true}
  validates :name, presence: true

  def populate_board
    @type = ""
    @row = nil
    @column = nil
    @player = nil

    (0..31).each do |i|
      if i < 8
        @row = 0
        @column = i
        @player = player_black_id
      elsif i < 16
        @row = 1
        @column = i - 8
        @player = player_black_id
      elsif i < 24
        @row = 6
        @column = i - 16
        @player = player_white_id
      else
        @row = 7
        @column = i - 24
        @player = player_white_id
      end

      if @row == 1 || @row == 6
        @type = "Pawn"
      elsif @column == 0 || @column == 7
        @type = "Rook"
      elsif @column == 1 || @column == 6
        @type = "Knight"
      elsif @column == 2 || @column == 5
        @type = "Bishop"
      elsif @column == 3
        @type = "Queen"
      else
        @type = "King"
      end

      Piece.create(game_id: self.id,user_id: @player,type: @type, row_pos: @row, col_pos: @column)
    end
  end

  def is_in_check?(player)
    my_king = Piece.where(user_id: player.id, type: 'King').first
    op_pieces = Piece.where('user_id != ? AND row_pos >= ?', player.id,0)
    op_pieces.each do |piece|
      if piece.valid_move?(my_king.row_pos,my_king.col_pos)
        return true
      end
    end
    return false
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :authenticate_user!, except: [:index]

    def index
        @games = Game.all
    end

    def new
        @game = Game.new
    end

    def create
        @game = Game.create(game_params)
        if @game.valid?
            @game.populate_board
    	    redirect_to game_path(@game)
        else
            render :new, :status => :unprocessable_entity
        end
    end

    def show
        @game = Game.where(:id => params[:id]).first
        if !@game.blank?
            @pieces = @game.pieces.to_a
            session[:current_game_id] = @game.id
	    else
            render :text => "Not found", :status => :not_found
        end
    end

    def update
        @game = Game.where(:id => params[:id]).first
	if current_user.id == @game.player_white_id
            redirect_to game_path(@game)
        else
            @game.update(:player_black_id => current_user.id)
            pieces = Piece.where(:game_id => @game.id, :user_id => 0)
            pieces.each {|p| p.update(:user_id => current_user.id)}
            redirect_to game_path(@game)
        end
    end


    private


    def game_params
        params.required(:game).permit(:name,:player_white_id, :player_black_id)
    end

    helper_method :get_piece_at_position
    helper_method :selected_piece
    helper_method :piece_color, :piece_finder
    helper_method :get_piece_color

    def get_piece_at_position(row, col)
        piece = @pieces.find { |p| p.row_pos == row && p.col_pos == col}
    end

    def selected_piece(row, col)
        piece = piece_finder(row, col)
        if piece
            @selected_piece = piece.type
        else
            @selected_piece = ""
        end
        @selected_piece
    end

    def get_piece_color(game, piece)
        # handle bad data
        return "" if game.nil? || piece.nil?

        return "Black" if piece.user_id == game.player_black_id
        return "White" if piece.user_id == game.player_white_id

        # the piece is not in this game!
        ""
    end

    def piece_color(row,col)
        piece = piece_finder(row,col)
        if piece
            if piece.user_id == @game.player_black_id
                color = "Black"
            elsif piece.user_id == @game.player_white_id
                color = "White"
            else
                color = ""
            end
        end
        color
    end

    def piece_finder(row,col)
        @pieces.find {|p| p.row_pos == row && p.col_pos == col}
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<div id="wrap"> 
<div class="hero">
<br />
<br />
<br />
<br />
 <div class="headline text-center">
 	<br />
 	<% if user_signed_in? %>
 	  <h1>Play ChessOnRails Now</h1>
 	<% else %>
 	  <h1>Join ChessOnRails Now</h1>
 	<% end %>
 	<br />
 	  <% if user_signed_in? %>
 	    <%= link_to 'Create a Game', new_game_path, :class => 'btn btn-primary btn-lg' %>
 	  <% else %>
 	    <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#MainModal">
 	      Sign Up
 	    </button>
 	  <% end %>
	  <div class="modal fade" id="MainModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	    <div class="modal-dialog">
	      <div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	          <h4 class="modal-title" id="myModalLabel">
	            <% if user_signed_in? %>
	              Play a Game
	            <% else %>
	              Sign Up
	            <% end %>
	          </h4>
	        </div>
	        <div class="modal-body">
	          <% if user_signed_in? %>
	            </br></br>
	            This is a placeholder for creating/joining a game.
	            </br></br></br>
			    <div class="actions modal-footer">
			        <button class="btn btn-warning">Create/Join</button>
			    </div>
	          <% else %>
			    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
			      <%= devise_error_messages! %>

			      <div class="field">
			        <%= f.label :email %><br />
			        <%= f.email_field :email, autofocus: true %>
			      </div>
				  <br />
			      <div class="field">
			        <%= f.label :password %>
			        <% if @minimum_password_length %>
			        <em>(<%= @minimum_password_length %> characters minimum)</em>
			        <% end %><br />
			        <%= f.password_field :password, autocomplete: "off" %>
			      </div>
				  <br />
			      <div class="field">
			        <%= f.label :password_confirmation %><br />
			        <%= f.password_field :password_confirmation, autocomplete: "off" %>
			      </div>
			      <br />
			      <div class="actions modal-footer">
			        <%= f.submit "Sign Up", :class => 'btn btn-warning' %>
			      </div>
			    <% end %>
			  <% end %>
	        </div>
	      </div>
	    </div>
	  </div>
 </div>
</div>

<br />

<div class="container col-xs-12 col-sm-12">
  <% @games.each do |game| %>
  <div class="booyah-box col-xs-4 col-sm-3 text-center">	
    <h1><%= game.name %></h1>
    <%= link_to "Join", game_path(game), :method => :put, :class => 'btn btn-primary'%>
  </div>
  <% end %>
</div>

</div>

app/views/games/new.html.erb
<div class="booyah-box col-xs-4 col-xs-offset-4 text-center">
  <h1>Create a Game</h1><br />

  <%= form_for @game do |f| %>
    <b>Enter a name for this game</b>
    <%= f.text_field :name %><br /><br />
    <%= f.hidden_field :player_white_id, :value => current_user.id %>
    <%= f.hidden_field :player_black_id, :value => 0 %>

    <%= f.submit 'Create', :class => 'btn btn-warning' %>
  <% end %>
</div>

app/views/games/show.html.erb
<div class="booyah-box col-xs-6 col-xs-offset-3 text-center">
<div id="wrap">

  <h1>Game On!</h1><br />

  <h2><%= @game.name %></h2><br />
  <% if @game.player_black.present? %>
    <% if @game.is_in_check?(@game.player_black) %>
      <p>Black is in check!</p>
    <% end %>
  <% end %>
  <% if @game.is_in_check?(@game.player_white) %>
    <p>White is in check!</p>
  <% end %>
  <p>Black</p>
  <% if @game.player_black.nil? %>
  <% else %>
  <%= @game.player_black.email %>
  <% end %>
<table>
  <tbody>
    <% selected_piece = @game.pieces.select { |p| p.is_selected }.first %>
    <% (0..7).each do |row| %>
       <tr>
        <% (0..7).each do |col| %>
       	  <td class="<%= "gray-space" if (col.even? && row.odd?) || (col.odd? && row.even?) %>">
         <!-- find out if there is a piece in the square -->          
          <% piece = piece_finder(row,col) %>    
          <% square_desc = "x" %>
            <% if piece %>
              <% square_desc = "#{piece_color(row, col)} #{piece.type}" %>
            <% end %>
          <!-- if there is a selected piece, draw move UI-->
            <% if selected_piece %>
              <% square_id = row * 8 + col %>
              <% if piece.nil? || piece.user_id != current_user.id %>
                <%= link_to square_desc, move_piece_path(square_id) %>
              <% elsif piece.user_id == current_user.id && piece.id != selected_piece.id %>
                <%= link_to square_desc, switch_piece_path(piece) %>
              <% else %>
                <strong><%= square_desc %></strong>
              <% end %>
            <% elsif piece %>
          <!-- if there is a piece and it's the current user's, draw select UI -->
              <% if piece.user_id == current_user.id %>
            		<%= link_to square_desc, select_piece_path(piece) %> 
          		<% else %>    
                <%= square_desc %>
              <% end %>                
            <% end %>             
          </td>
        <% end %>  
     </tr>
 	  <% end %>
  </tbody>
</table>
<br /><br />

<p>White</p>
<%= @game.player_white.email %>

</div>
</div>